import { Product } from "@/types/product"

export const mockProducts: Product[] = [
  {
    id: "auto-report-1",
    slug: "auto-report-generator",
    name: "AutoReport Pro",
    tagline: "Automated reporting that writes itself",
    description: "Generate comprehensive business reports automatically from your data sources. Connect to databases, APIs, and spreadsheets to produce polished PDF and Excel reports on schedule.",
    category: "Automation",
    type: "web-application",
    price: 299,
    pricingModel: "one-time",
    image: "/images/product-1.jpg",
    features: [
      "Connect to 50+ data sources",
      "Schedule automated reports",
      "PDF & Excel export",
      "Custom branding",
      "Email delivery",
    ],
    timeSaved: "15 hours/week",
    moneySaved: "$2,400/month",
    rating: 4.9,
    reviews: 127,
    downloads: 843,
    tags: ["reporting", "automation", "business"],
  },
  {
    id: "data-scraper-1",
    slug: "universal-data-scraper",
    name: "DataScraper X",
    tagline: "Extract any data from any website",
    description: "Powerful web scraping tool with intelligent anti-detection, proxy rotation, and structured data export. No coding required for basic tasks.",
    category: "Scraping",
    type: "cli-tool",
    price: 149,
    pricingModel: "one-time",
    image: "/images/product-2.jpg",
    features: [
      "Visual selector builder",
      "Anti-bot detection bypass",
      "Proxy rotation built-in",
      "JSON/CSV/Excel export",
      "Scheduled scraping jobs",
    ],
    timeSaved: "20 hours/week",
    moneySaved: "$3,600/month",
    rating: 4.8,
    reviews: 89,
    downloads: 621,
    tags: ["scraping", "data", "automation"],
  },
  {
    id: "email-bot-1",
    slug: "smart-email-responder",
    name: "MailMind AI",
    tagline: "AI-powered email automation",
    description: "Intelligent email processing that reads, categorizes, and responds to your emails using custom rules and AI. Integrates with Gmail, Outlook, and custom IMAP.",
    category: "AI",
    type: "desktop-tool",
    price: 49,
    pricingModel: "monthly",
    image: "/images/product-3.jpg",
    features: [
      "AI email categorization",
      "Smart auto-responses",
      "Template system",
      "Analytics dashboard",
      "Multi-account support",
    ],
    timeSaved: "10 hours/week",
    moneySaved: "$1,800/month",
    rating: 4.7,
    reviews: 203,
    downloads: 1156,
    tags: ["email", "ai", "productivity"],
  },
  {
    id: "invoice-auto-1",
    slug: "invoice-automation-suite",
    name: "InvoiceFlow",
    tagline: "From quote to paid in zero clicks",
    description: "End-to-end invoice automation. Generate, send, track, and reconcile invoices automatically. Integrates with Stripe, PayPal, and bank APIs.",
    category: "Finance",
    type: "web-service",
    price: 79,
    pricingModel: "monthly",
    image: "/images/product-4.jpg",
    features: [
      "Auto invoice generation",
      "Payment gateway integration",
      "Late payment reminders",
      "Tax calculation",
      "Multi-currency support",
    ],
    timeSaved: "8 hours/week",
    moneySaved: "$1,200/month",
    rating: 4.9,
    reviews: 156,
    downloads: 934,
    tags: ["finance", "invoicing", "automation"],
  },
  {
    id: "social-auto-1",
    slug: "social-media-automator",
    name: "SocialPulse",
    tagline: "Your social media runs itself",
    description: "Schedule, publish, and analyze across all major social platforms. AI-generated captions, optimal timing, and engagement analytics.",
    category: "Marketing",
    type: "web-application",
    price: 39,
    pricingModel: "monthly",
    image: "/images/product-5.jpg",
    features: [
      "Multi-platform publishing",
      "AI caption generation",
      "Optimal timing algorithm",
      "Engagement analytics",
      "Hashtag research",
    ],
    timeSaved: "12 hours/week",
    moneySaved: "$2,100/month",
    rating: 4.6,
    reviews: 312,
    downloads: 2045,
    tags: ["social-media", "marketing", "ai"],
  },
  {
    id: "backup-script-1",
    slug: "enterprise-backup-automation",
    name: "SafeGuard Scripts",
    tagline: "Bulletproof backup automation",
    description: "Enterprise-grade backup scripts for databases, files, and cloud resources. Incremental backups, encryption, and disaster recovery.",
    category: "DevOps",
    type: "script",
    price: 199,
    pricingModel: "one-time",
    image: "/images/product-6.jpg",
    features: [
      "Database backup scripts",
      "Cloud sync automation",
      "Encryption at rest",
      "Disaster recovery plans",
      "Monitoring & alerts",
    ],
    timeSaved: "5 hours/week",
    moneySaved: "$900/month",
    rating: 5.0,
    reviews: 67,
    downloads: 445,
    tags: ["devops", "backup", "security"],
  },
]

export const stats = [
  { label: "Hours Saved", value: "50,000+", suffix: "hrs" },
  { label: "Money Saved", value: "$2.4M", suffix: "" },
  { label: "Active Clients", value: "1,200+", suffix: "" },
  { label: "Products", value: "50+", suffix: "" },
]

export const howItWorks = [
  {
    step: 1,
    title: "Discover",
    description: "Browse our catalog of battle-tested automation tools or request a custom solution tailored to your workflow.",
    icon: "search",
  },
  {
    step: 2,
    title: "Deploy",
    description: "One-click installation or guided setup. Our tools integrate seamlessly with your existing stack.",
    icon: "rocket",
  },
  {
    step: 3,
    title: "Automate",
    description: "Watch repetitive tasks disappear. Your team focuses on what matters while the software handles the rest.",
    icon: "zap",
  },
  {
    step: 4,
    title: "Scale",
    description: "As your business grows, our solutions scale with you. Upgrade, customize, or build new automations.",
    icon: "trending-up",
  },
]
